# https://taskfile.dev

version: "3"

vars:
  PROJECT: Yanko

tasks:
  default:
    cmds:
      - mamba run --live-stream -n {{.PROJECT}} python app.py {{.CLI_ARGS}}
    silent: true

  notunes:
    desc: disable hotkey handling
    cmds:
      - launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  export:
    desc: export env
    cmds:
      - mamba env export --no-builds  -n {{.PROJECT}} > environment.yml

  build:
    cmds:
      - rm -rf build || true
      - rm -rf dist || true
      - rm -rf .eggs || true
      - mamba run --live-stream -n {{.PROJECT}} python setup.py py2app

  install:
    cmds:
      - killall {{.PROJECT}} || true
      - rm -rf /Applications/{{.PROJECT}}.app
      - mv dist/{{.PROJECT}}.app /Applications

  dmg:
    desc: create dmg file
    cmds:
      - echo "create DMS"
      - rm -f {{.PROJECT}}.dmg
      - ./node_modules/.bin/appdmg {{.PROJECT}}.json {{.PROJECT}}.dmg

  deploy:
    desc: push + build + dmg + install
    cmds:
      - task: build
      - task: push
      - task: dmg
      - task: install
