# https://taskfile.dev

version: '3'

vars:
  PROJECT: Yanko

tasks:
  default:
    cmds:
      - poetry run python app.py
    silent: true

  notunes:
    desc: disable hotkey handling
    cmds:
      - launchctl unload -w /System/Library/LaunchAgents/com.apple.rcd.plist

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  build:
    cmds:
      - rm -rf build 
      - rm -rf dist
      - rm -rf .eggs
      - poetry run python setup.py py2app

  install:
    cmds:
      - killall {{.PROJECT}} || true
      - rm -rf /Applications/{{.PROJECT}}.app
      - mv dist/{{.PROJECT}}.app /Applications

  dmg:
    desc: create dmg file
    cmds:
      - echo "create DMS"
      - rm -f {{.PROJECT}}.dmg
      - ./node_modules/.bin/appdmg {{.PROJECT}}.json {{.PROJECT}}.dmg

  deploy:
    cmds:
      - poetry run python app.py increment_version
      - task: push
      - task: build
      - task: dmg
      - task: install

